GoogleCloudPlatform/cloudml-samples

- reddit_tft/README.md
Change December link (followed to January)
> Correct link to test data

- flowers/sample.sh
See http://stackoverflow.com/questions/43079274/runtime-version-versus-runtime-version-in-cloudml-samples-flowers-sample-sh
> Change runtime_version to runtime-version

- TESTING.md
- criteo_tft/README.md
- criteo_tft/requirements.txt
- flowers/README.md
- testing/ubuntu/presubmit/common.cfg
- testing/ubuntu/presubmit/flowers.cfg
- testing/ubuntu/presubmit/run_if_changed.sh
- testing/ubuntu/release/common.cfg
- testing/ubuntu/release/flowers.cfg
- testing/ubuntu/setup_and_run_test.sh
@elmer-garduno @nkashy1 @dizcology  Added requirements.txt for criteo.
> updated README and added requirements.txt

- census/README.md
- census/customestimator/trainer/task.py
- census/estimator/trainer/task.py
- census/tensorflowcore/trainer/task.py
@rhaertel80 @nkashy1 Added model checkpoint reuse flag so that people don't trip over model checkpointing issue when same model gets reused.
> Model checkpoint

- contrib/README.md
@nkashy1 @dizcology @rhaertel80 Created a place to host contrib samples as we have plans to add some.
> Contrib samples

- CONTRIBUTING.md
- README.md
@nkashy1 @rhaertel80 @dizcology @sgreenberg @jingjinglong
> Readme improved

- criteo_tft/README.md
- movielens/README.md
- reddit_tft/README.md
> Readme fix

- movielens/README.md
Clarify that the ml-latest-small dataset should be used when running locally
> Clarify which dataset to use to run locally

- movielens/requirements.txt
- movielens/setup.py
@elmer-garduno Movielens fix in package and requirements.txt import
> made fix to requirements.txt

- census/keras/requirements.txt
- census/keras/trainer/model.py
- census/requirements.txt
- census/tensorflowcore/trainer/task.py
- flowers/requirements.txt
- flowers/trainer/model.py
- mnist/deployable/trainer/task.py
- mnist/distributed/trainer/model.py
This reverts commit 5b6b901c80e87770dc836f0e64e6eeb3c073efef.
@rhaertel80 Please confirm if the revert looks good and then we can merge with master.
> Revert "Now using simple_save to export models."

- census/README.md
update args to saved_model_cli example in census README
> update census README

- README.md
- census/README.md
- criteo_tft/README.md
- flowers/README.md
- movielens/README.md
- reddit_tft/README.md
Added to the index in the top-level README as well as to the READMEs for
the indexed models.
> Added problem descriptions

- census/README.md
- census/customestimator/trainer/task.py
- census/estimator/trainer/model.py
- census/estimator/trainer/task.py
- census/keras/README.md
- census/keras/trainer/task.py
- census/tensorflowcore/trainer/task.py
@elmer-garduno @nkashy1 This is the change to make sure the code works with Py2/Py3 using python interpreter and gcloud. Please verify and preferably try it out. I have already done so but another pair of eyes will be helpful. The gcloud fix now works with Python3 and so this change.
> fixed the import so it works with python3 and python2

- census/estimator/trainer/model.py
Code style clean up. 
This is my first pull request. Please advise if there is anything I did wrong.
Thanks,
> Fix code style - this line is not a docstring, changing it to a comment

- flowers/requirements.txt
- flowers/sample.sh
Worked with minimal changes - tested several times locally and on GCP.
> Flowers sample updated to use TensorFlow 1.4

- README.md
- sklearn/notebooks/Online Prediction with scikit-learn.ipynb
- xgboost/notebooks/Online Prediction with XGBoost.ipynb
some sklearn notebook fixes as well.
> add xgboost online prediction notebook

- census/estimator/trainer/task.py
device_filters should be set to avoid communication between master and all the workers. Rather the communication must be made between master <-> ps and worker <-> ps.
> Added device_filters to session_config

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/sample-feature-request.md
Add new templates for sample/feature requests and a new bug report template that includes wording for scikit-learn and tensorflow. 
Linked to: https://github.com/GoogleCloudPlatform/cloudml-samples/pull/230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/232)
> Update issue templates

- census/estimator/trainer/model.py
[#237](https://github.com/GoogleCloudPlatform/cloudml-samples/issues/237)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/238)
> address issue #237

- sklearn/iris_training.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/242)
> change `bucket` to `BUCKET_ID`

- xgboost/iris_training.py
The correct variable name is BUCKET_ID
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/255)
> Fixing the wrong variable name

- tpu/templates/README.md
- tpu/templates/tools/README_BASE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/263)
> fix readme

- flowers/requirements.txt
- flowers/sample.sh
- testing/ubuntu/setup_and_run_test.sh
1. Update Apache Beam version to 2.6.0
2. Update Bucket repositories.
3. Add GOOGLE_APPLICATION_CREDENTIALS definition
These 3 changes were created together in order for presubmit tests to pass.
Other past Pull requests have been failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/253)
> Update Flowers repository with new Buckets.

- xgboost/notebooks/XGBoost Hyperparameter Tuning.ipynb
Removed the output print outs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/272)
> Removed the output

- reddit_tft/requirements.txt
- reddit_tft/setup.py
@elmer-garduno Reddit version fix. It was failing before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/157)
> added version fixes and six

- census/customestimator/trainer/model.py
- census/customestimator/trainer/task.py
- census/estimator/trainer/model.py
- census/estimator/trainer/task.py
- census/keras/trainer/model.py
- census/keras/trainer/task.py
- census/sample.sh
- census/tensorflowcore/trainer/model.py
- census/tensorflowcore/trainer/task.py
- census/tftransformestimator/trainer/model.py
- census/tftransformestimator/trainer/task.py
-Keep the same format for input arguments across all samples.
-Fix import arguments to handle single file string. (Rename filenames to filename)
train-files -> train-file
eval-files -> eval-file
-Add documentation to methods.
-Rearrange and cleanup imports.
-Update sample.sh to handle new names.
Tested with TF 1.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/282)
> Cleanup Model and Task files.

- tpu/utils/README.md
- tpu/utils/requirements.txt
- tpu/utils/submit_preemptible.sh
- tpu/utils/tpu_survival.py
- tpu/utils/tpu_survival_job.py
- tpu/utils/tpu_utils.py
* tpu utils for managing tpu resrouces (list, get, create, delete)
* tpu survival for resuming training when using preemptible tpus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/290)
> Tpu utils and survival

- flowers/images_to_json.py
- flowers/pipeline.py
- flowers/trainer/task.py
- iris/pipeline.py
- iris/preprocess.py
- mnist/distributed/local_predict.py
- mnist/distributed/trainer/task.py
- mnist/hptuning/trainer/task.py
- movielens/preprocess.py
- movielens/trainer/task.py
See #287
These changes are compatible with both Python 2 and Python 3.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/289)
> Modernize Python 2 code to get ready for Python 3

- imdb/README.md
- imdb/tensorflow/keras/requirements.txt
- imdb/tensorflow/keras/setup.py
- imdb/tensorflow/keras/trainer/model.py
- imdb/tensorflow/keras/trainer/task.py
- imdb/tensorflow/keras/trainer/utils.py
-Update args Move args from - to _
-Update README.md with correct args
-Rename function
-Add PREDICT support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/293)
> IMDB Keras cleanup

- molecules/predict.py
- molecules/preprocess.py
- molecules/pubchem/pipeline.py
The docs have already been frozen to the latest commit in preparation for this change, so the links will not break. I will update the docs once this is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/299)
> Update Dataflow region tags to standard format

- criteo_tft/preprocess.py
this way it works in cloud mode, avoids ErrorName error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/313)
> move import inside function

- census/customestimator/trainer/task.py
- census/estimator/trainer/task.py
- census/keras/preprocess.py
- census/keras/trainer/task.py
- census/tensorflowcore/trainer/task.py
- census/tftransformestimator/trainer/task.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/316)
> Remove contrib dependencies

- census/README.md
Link to TFT Transform Estimator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/330)
> Fix census readme broken link

- reinforcement_learning/rl_on_gcp_demo/README.md
- reinforcement_learning/rl_on_gcp_demo/start.sh
Hi,
I've added the url to the blog post.
Plan to modify the code to conform to tf_agent.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/337)
> RL on GCP (#3)

- sklearn/iris_training.py
- xgboost/iris_training.py
Mostly tweaking comments and variable names. Adds an argument to `svm.SVC()` to quiet an sklearn deprecation warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/340)
> Tidy sklearn and xgboost iris_training.py

- reddit_tft/preprocess.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/361)
> fix random import in preprocess.py

- README.md
- pytorch/README.md
- tensorflow/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/362)
> Add new samples to high level READMEs

- tpu/templates/tools/SUB_README_BASE.md
- tpu/templates/tools/sub_readme_gen.py
- tpu/templates/tpu_cnn_estimator/trainer_readme.md
- tpu/templates/tpu_estimator/trainer_readme.md
- tpu/templates/tpu_film_estimator/trainer_readme.md
- tpu/templates/tpu_gan_estimator/trainer_readme.md
- tpu/templates/tpu_gan_estimator/trainer_single_readme.md
- tpu/templates/tpu_grl_estimator/trainer_readme.md
- tpu/templates/tpu_lstm_estimator/trainer_readme.md
- tpu/templates/tpu_lstm_keras/trainer_readme.md
- tpu/templates/tpu_rewrite/trainer_infeed_outfeed_readme.md
- tpu/templates/tpu_rewrite/trainer_readme.md
- tpu/templates/tpu_triplet_loss_estimator/trainer_readme.md
simple readme files for individual templates, generated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/372)
> add sub readme files for tpu templates

- notebooks/scikit-learn/Training and Prediction with scikit-learn.ipynb
- notebooks/xgboost/Training and Prediction with XGBoost.ipynb
Rename scikit learn notebook
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/383)
> Add XGBoost notebook

- census/README.md
- census/tf-keras/README.md
- census/tf-keras/requirements.txt
- census/tf-keras/trainer/model.py
- census/tf-keras/trainer/task.py
- census/tf-keras/trainer/util.py
- notebooks/tensorflow/getting-started-keras.ipynb
Made all the last changes that Crystal suggested, specifically: 
* made setup instructions as specific as possible for different environments
* added output cells
I've done some cleanup on the output cells to make them as generally applicable as possible:
* replaced my personal project and bucket names with `<your-project-id>` and `<your-bucket-name>` in the logs
* Made sure the cell execution numberings reads as a clear 1 through 39 (even though I didn't always run them in exactly in order/ran some cells more than once ☺️)
The log outputs for the training job take up a lot of space, but Colab and the local Jupyter environment add a scrollbar so it's not awful to work with, just perhaps annoying to look at in GitHub. It may be worth setting the trainer to run for fewer epochs (e.g. 5 …
> Getting started in Keras tutorial notebook

- notebooks/tensorflow/getting-started-keras.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/390)
> Add link to Keras tutorial on cloud.google.com, additional storage info

- sklearn/README.md
Solves issue #394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/395)
> fix broken paths in the scikit-learn README.md

- census/README.md
- census/estimator/requirements.txt
- census/requirements.txt
- census/tf-keras/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/393)
> Update TF to 1.13 in Census project

- notebooks/tensorflow/getting-started-keras.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/401)
> Fix malformed string in notebook

- tensorflow/standard/mnist/README.md
Underscore to hyphen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/402)
> Typo in flag name

- notebooks/scikit-learn/custom-pipeline.ipynb
- notebooks/scikit-learn/custom-prediction-routine-scikit-learn.ipynb
- notebooks/tensorflow/custom-prediction-routine-keras.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/406)
> Add notebooks for custom code beta launch

- notebooks/scikit-learn/20_newsgroups_automl.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/407)
> Added notebook which preprocesses sklearn data for import into AutoML NL

- notebooks/tensorflow/getting-started-keras.ipynb
Tiny fix 😄
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/409)
> Fix link anchor

- cloudml-template/scripts/cloudml-deploy-model.sh
- cloudml-template/scripts/cloudml-submit-train-job.sh
- cloudml-template/scripts/local-train.sh
Move gcloud ml-engine to gcloud ai-platform
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/414)
> Update MLE engine commands to AI Platform

- notebooks/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/416)
> Add high level README for what this folder is about

- CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/418)
> Add Code owners to be added for reviews

- sklearn/sklearn-template/template/trainer/model.py
- sklearn/sklearn-template/template/trainer/utils.py
This PR is to fix the bugs in sklearn template. The previous version will raise exception for the case the there is no certain type of features, e.g. numerical or categorical.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/417)
> fix bugs for numerical and categorical feature filtering in sklearn template

- .gitignore
- molecules/.gitignore
- molecules/README.md
- molecules/data-extractor.py
- molecules/predict.py
- molecules/preprocess.py
- molecules/pubchem/__init__.py
- molecules/pubchem/pipeline.py
- molecules/pubchem/sdf.py
- molecules/publisher.py
- molecules/requirements.txt
- molecules/run-cloud
- molecules/run-local
- molecules/setup.py
- molecules/subscriber.py
- molecules/trainer/__init__.py
- molecules/trainer/task.py
* Added a `--region` option to `run-cloud` to address issue #392 
* Fixed validation error to address issue #426
* Updated to Apache Beam 2.11 and TensorFlow 1.13
* Made Python 3 compatible (although still not recommended since it's in alpha stage)
* Added `.gitignore`
* Overall code cleanups
* Updated README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/427)
> Molecules update

- tensorflow/containers/unsupported_runtime/task.py
name correction pytorch --> keras on tensorflow/containers/unsupported_runtime/task.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/432)
> name correction pytorch --> keras

- tensorflow/containers/unsupported_runtime/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/435)
> Updates a command (ml-engine to ai-platform)

- pytorch/containers/quickstart/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/434)
> Updates a README for custom containers.

- census/keras/trainer/task.py
Tried to run and got errors with the defaults, noticed they expect n+ args. Made the defaults an array so the code runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/440)
> Fix census keras sample defaults

- notebooks/pytorch/Text Classification Using PyTorch and CMLE.ipynb
Add warning to note that the sample is broken while we wait for the product team to fix the backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/441)
> Update Text Classification Using PyTorch and CMLE.ipynb

- notebooks/tensorflow/getting-started-keras.ipynb
Solves two bugs that were fixed on the cloud.google.com version of this tutorial already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/462)
> Fix variable interpolation, update Storage restriction

- pytorch/containers/hp_tuning/data_utils.py
> fix: Change bucket path logic in data_utils.py
