GoogleCloudPlatform/cloudml-samples

- census/keras/README.md
- census/keras/trainer/task.py
For now h5py can't save files directly to GCS paths, this is a hack to work around the problem.
> Workaround for copying h5py to GCS

- census/keras/README.md
Updated the "Training using Cloud ML Engine" command example to use the version 1.4 of Tensor Flow, now used in this sample.
> Now needs TF v1.4

- census/README.md
Addresses the tf 1.4-related export path changes for the estimator example.  Also figured we might as well run the cmle training for more steps than locally.
Note: I did *not* check to see if the following re: the low level example had also changed.  It may need to be updated too.
* Low Level Based: You should see a directory named `$GCS_JOB_DIR/export/JSON/`
for `JSON`. See other formats `CSV` and `TFRECORD`.
> readme updates to reflect 1.4 changes

- census/README.md
A couple other small suggestions — what do you think of generating a date-stamped job name?  You can't reuse the job names, and so that will let them more easily rerun. (And also lets the job dir be more easily unique for each run).
Also, it might be useful to echo `$GCS_JOB_DIR` b/c they'll need that for finding the exported model.
> minor README mods, generate date-stamped job names for CMLE

- census/customestimator/trainer/model.py
Unless `tf.squeeze` is given an explicit list of axis to squeeze which does not include the batch dimension, it will squeeze batch sizes of 1 into scalars, which will cause `sparse_softmax_cross_entropy_with_logits` to fail with a shape error. This only happens in training if a `allow_final_batches=True` is allowed to trigger, which must require a restriction not based on number of steps but based on epochs.
> Restrict squeeze dims to prevent squeezing out batch dim

- census/estimator/trainer/model.py
The previous input function was incorrect in the presence of multiple filenames:
1. The filenames were never shuffled.
2. The header lines were only skipped from the first file, and header lines in subsequent files would be included in the output.
> Fix shuffling and header line handling in `input_fn()`

- census/keras/trainer/model.py
- census/keras/trainer/task.py
Fix to enable the input generator to iterate over multiple file chunks and return to the file begging when reaching the end.
Also updated the feature extractor `to_numeric_features()` to return a consistent dataframe schema: the categorical classes are 'one hot' encoded based on the available values in the processed chunk, hence the returned column list may vary from a chunk to another (if new values are found or old are missing).
Added a mini-batch functionality to the generator_input (previous version returning one sample at a time). Training on generated mini-batches considerably* improves the performances. (I do not know how to reliably measure this on Google Cloud - this version seems to consume a 5th of the ML units and a 20th of the time, compared to the previous one, for the same …
> Census Keras input generator fix

- cloudml-template/README.md
- cloudml-template/examples/babyweight-custom/trainer/task.py
- cloudml-template/examples/census-classification/trainer/task.py
- cloudml-template/examples/german-custom/trainer/task.py
- cloudml-template/examples/housing-regression/trainer/task.py
- cloudml-template/scripts/cloudml-submit-train-job.sh
- cloudml-template/template/trainer/task.py
@puneith - I have made the following (minor) updates to the cloudml-template template & examples:
- Updating the --num-epoch default value to None, since it's use is not relevant unless the --train-size and the --train-batch-size parameters are specified, otherwise the --train-steps is used.
- Simplified the example script to submit a training job to CMLE, including only the necessary arguments
Note that the same exact changes were applied to the template, and the 4 examples.
These changes managed to resolve this issue #203
> cloudml-template - updating the default params

- reddit_tft/preprocess.py
It seams like the latest google-cloud-dataflow (now 2.4.0) do not loads the default project for bigquery
The pipeline only parse the command line options if passed as `argv` argument ([docs](https://beam.apache.org/documentation/sdks/pydoc/2.4.0/apache_beam.pipeline.html#apache_beam.pipeline.Pipeline)), so doing what the error message suggests, add `--project [PROJECT_ID]` as a command line option, does not work
I can think of two solutions to this problem:  
1. Pass the unkown command line options to the `argv` argument of the pipeline
1. Build a `PipelineOptions` object for the Direct Runner, not only the Dataflow Runner
I used the second one to avoid having two redundant arguments (`--project_id` and `--project`)
> Added project to DirectRunner pipeline options on Reddit TFT

- census/keras/trainer/model.py
Changing the ```softmax``` activation to `sigmoid` activation at Line 73. Because if `labels_dim` is 1 then having `softmax` activation may have bad performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/241)
> changing sofmax to sigmoid

- reddit_tft/README.md
Also, @lamberta told me `TFRecord` is preferable to `TFRecords`.
(I'm making this fix on https://cloud.google.com/ml-engine/docs/tensorflow/samples so I figured I'd mirror it here.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/266)
> Swap out broken Tensorflow docs link

- census/estimator/trainer/model.py
Update model.py to handle single filename as string, versus expecting a list of files.
Tested successfully in local, gcloud local and gcloud ml-engine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/276)
> Handle single filename as string

- movielens/preprocess.py
Adding random import into method. Imports, functions and other variables defined in the global context of your main file of your Dataflow pipeline are, by default, not available in the worker execution environment, and such references will cause a NameError.
Please see https://cloud.google.com/dataflow/faq#how-do-i-handle-nameerrors for additional documentation on configuring your worker execution environment.
Reported here: Issue #250
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/254)
> Update preprocess.py to handle NameError

- census/keras/trainer/task.py
when `monitor='val_loss'`, we should use `mode='min'` according the Keras documentation https://keras.io/callbacks/#modelcheckpoint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/118)
> Updated mode='min' for the ModelCheckpoint

- molecules/pubchem/pipeline.py
```
cann -> can
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/349)
> Fix typo in function doc-string

- CONTRIBUTING.md
Remove extra space between `]` and `(` to ensure proper inline
rendering of the HTML links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/347)
> Fix Markdown formatted links for CLA

- pytorch/containers/quickstart/mnist/Dockerfile
- pytorch/containers/quickstart/mnist/Dockerfile-gpu
There is an issue with latest torch version: https://github.com/pytorch/pytorch/issues/16775
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/364)
> Using fixed version for torch in MNIST custom container sample

- cloudml-template/template/trainer/input.py
This is achieved by calling batching the raw input first and then
calling the map function for each batch. This follows the considerations
described [here](https://www.tensorflow.org/guide/performance/datasets#map_and_batch).
In a related project this change boosted throughput on a CSV dataset by
a factor of 2.
Finally, now the pipeline support skipping the header for every CSV
file. Before it was failed if the CSV dataset consisted of multiple
files each with a header.
P.S. after speaking with @gogasca this will be the first of several improvements. I wonder if I should open one/several issues to track this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samp …
> This change improve the input_pipeline performance.

- cloudml-template/scripts/cloudml-submit-train-job.sh
- cloudml-template/template/setup.py
- cloudml-template/template/trainer/input.py
- cloudml-template/template/trainer/task.py
This is part of a series of improvements tracked in
GoogleCloudPlatform/cloudml-samples#366 .
This is done by adding 2 new input_receivers_functions (prepended with
tfma_ in the code) and an additional export in task.py.
The template now depends on tfma consequently tf==1.12.0. Therefore,
these dependencies have been updated in setup.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/367)
> This change adds support for the Tensorflow Model Analysis.

- molecules/README.md
The url was to the ML Engine and not AI Platform, which is the correct according to the recent renaming operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/405)
> Fixed Renaming to AI Platform, wrong url

- notebooks/scikit-learn/custom-pipeline.ipynb
- notebooks/scikit-learn/custom-prediction-routine-scikit-learn.ipynb
- notebooks/tensorflow/custom-prediction-routine-keras.ipynb
This addresses #419 by making sure the version of scikit-learn (and thus joblib) used during training matches the version of scikit-learn (and thus joblib) used during prediction in AI Platform runtime version 1.13.
[Run the update notebook in Colab.](https://colab.research.google.com/github/GoogleCloudPlatform/cloudml-samples/blob/alecglassford-patch-5/notebooks/scikit-learn/custom-prediction-routine-scikit-learn.ipynb)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/421)
> Specify training dependency versions (fixes #419)

- census/tensorflowcore/trainer/model.py
- census/tensorflowcore/trainer/task.py
Doing census tutorial at https://cloud.google.com/ml-engine/docs/tensorflow/getting-started-training-prediction
Tried to run in python3 runtime but the code was not compatible, I fixed it and now run correctly in both python2 and python3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/424)
> python2 -> python3 for census/tensorflowcore tutorial

- molecules/README.md
In initial setup step, add creating ADC step since ‘./run-cloud’ command requires it.
See also : https://stackoverflow.com/questions/44401088/using-training-tfrecords-that-are-stored-on-google-cloud
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/428)
> Add instruction to README.md of molecules

- notebooks/scikit-learn/20_newsgroups_automl.ipynb
AutoML Natural Language previously allowed labels such as `comp.graphics` but would change them to become valid, e.g. `comp_graphics`. Now, AutoML NL throws an error.
The change in the notebook is to add this step:
```
df['categories'] = df['categories'].str.replace('.','_')
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/450)
> Added cleanup step to remove unsupported characters in labels

- census/tf-keras/trainer/util.py
- notebooks/scikit-learn/custom-pipeline.ipynb
- notebooks/tensorflow/getting-started-keras.ipynb
- sklearn/notebooks/census_training/train.py
- xgboost/iris_training.py
- xgboost/notebooks/census_training/train.py
There's a new gs://cloud-samples-data/ai-platform/ directory with all the same contents as gs://cloud-samples-data/ml-engine/.
gs://cloud-samples-data/ml-engine/ is referenced in a lot of places in this repository, and I don't think it's necessary to change every instance (nor do I want to, at the risk of breaking something).
This PR just changes instances that are included/referenced directly in the AI Platform documentation, in order to improve branding with in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/454)
> Use gs://cloud-samples-data/ai-platform/ directory for docs

- renovate.json
TensorFlow 1.x to 2.x was a major upgrade. Automatic upgrades will break notebooks.
> chore: Exclude TensorFlow from Renovate updates
